### ISSUE TITLE
doesn't work with latest version of timbre 4.3.1

### ISSUE THREAD

**Issue by jasonjckn** [fzakaria/slf4j-timbre#16]
`push_listings_index | 16-03-16 20:56:06 565cd3e3f185 INFO [push-listings-index.main:44] - Created new listings index
push_listings_index | Exception in thread "main" java.lang.IllegalStateException: Attempting to call unbound fn: #'taoensso.timbre/log1-fn, compiling:(/tmp/form-init816281410483448011.clj:1:72)
push_listings_index |   at clojure.lang.Compiler.load(Compiler.java:7391)
push_listings_index |   at clojure.lang.Compiler.loadFile(Compiler.java:7317)
push_listings_index |   at clojure.main$load_script.invokeStatic(main.clj:275)
push_listings_index |   at clojure.main$init_opt.invokeStatic(main.clj:277)
push_listings_index |   at clojure.main$init_opt.invoke(main.clj:277)
push_listings_index |   at clojure.main$initialize.invokeStatic(main.clj:308)
push_listings_index |   at clojure.main$null_opt.invokeStatic(main.clj:342)
push_listings_index |   at clojure.main$null_opt.invoke(main.clj:339)
push_listings_index |   at clojure.main$main.invokeStatic(main.clj:421)
push_listings_index |   at clojure.main$main.doInvoke(main.clj:384)
push_listings_index |   at clojure.lang.RestFn.invoke(RestFn.java:421)
push_listings_index |   at clojure.lang.Var.invoke(Var.java:383)
push_listings_index |   at clojure.lang.AFn.applyToHelper(AFn.java:156)
push_listings_index |   at clojure.lang.Var.applyTo(Var.java:700)
push_listings_index |   at clojure.main.main(main.java:37)
push_listings_index | Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'taoensso.timbre/log1-fn
push_listings_index |   at clojure.lang.Var$Unbound.throwArity(Var.java:43)
push_listings_index |   at clojure.lang.AFn.invoke(AFn.java:62)
push_listings_index |   at slf4j_timbre.adapter$_info$inner__2062__auto____2103.invoke(adapter.clj:46)
push_listings_index |   at clojure.lang.AFn.applyToHelper(AFn.java:154)
push_listings_index |   at clojure.lang.AFn.applyTo(AFn.java:144)
push_listings_index |   at clojure.core$apply.invokeStatic(core.clj:646)
push_listings_index |   at clojure.core$apply.invoke(core.clj:641)
push_listings_index |   at slf4j_timbre.adapter$_info.doInvoke(adapter.clj:46)
push_listings_index |   at clojure.lang.RestFn.invoke(RestFn.java:423)
push_listings_index |   at com.github.fzakaria.slf4j.timbre.TimbreLoggerAdapter.info(Unknown Source)
push_listings_index |   at com.mongodb.diagnostics.logging.SLF4JLogger.info(SLF4JLogger.java:71)
push_listings_index |   at com.mongodb.connection.SingleServerCluster.<init>(SingleServerCluster.java:45)
push_listings_index |   at com.mongodb.connection.DefaultClusterFactory.create(DefaultClusterFactory.java:85)
push_listings_index |   at com.mongodb.Mongo.createCluster(Mongo.java:683)
push_listings_index |   at com.mongodb.Mongo.createCluster(Mongo.java:669)
push_listings_index |   at com.mongodb.Mongo.createCluster(Mongo.java:643)
push_listings_index |   at com.mongodb.Mongo.<init>(Mongo.java:290)
push_listings_index |   at com.mongodb.MongoClient.<init>(MongoClient.java:268)
push_listings_index |   at monger.core$connect_via_uri.invokeStatic(core.clj:195)
push_listings_index |   at monger.core$connect_via_uri.invoke(core.clj:195)
push_listings_index |   at push_listings_index.mongo$oplog_HEAD_ts_BANG_.invokeStatic(mongo.clj:43)
push_listings_index |   at push_listings_index.mongo$oplog_HEAD_ts_BANG_.invoke(mongo.clj:41)
push_listings_index |   at push_listings_index.main$_main.invokeStatic(main.clj:50)
push_listings_index |   at push_listings_index.main$_main.doInvoke(main.clj:40)
push_listings_index |   at clojure.lang.RestFn.invoke(RestFn.java:397)
push_listings_index |   at clojure.lang.Var.invoke(Var.java:375)
push_listings_index |   at user$eval5.invokeStatic(form-init816281410483448011.clj:1)
push_listings_index |   at user$eval5.invoke(form-init816281410483448011.clj:1)
push_listings_index |   at clojure.lang.Compiler.eval(Compiler.java:6927)
push_listings_index |   at clojure.lang.Compiler.eval(Compiler.java:6917)
push_listings_index |   at clojure.lang.Compiler.load(Compiler.java:7379)
push_listings_index |   ... 14 more`

When I reverted to timbre 4.2.1 it fixed the problem

**Comment by rufoa** [comment]
Thanks, will investigate

**Comment by rufoa** [comment]
this is resolved in the upcoming v0.3.1

@fzakaria: could you merge https://github.com/fzakaria/slf4j-timbre/pull/14 into master and push a new jar to clojars please

**Comment by fzakaria** [comment]
Will do

**Comment by fzakaria** [comment]
@rufoa 0.3.1 is released.

**Comment by fzakaria** [comment]
if problem is resolved let me know and we can close the issue.

**Comment by rufoa** [comment]
thanks!

@jasonjckn please upgrade to 0.3.1 and try again

**Comment by jasonjckn** [comment]
Nice work guys!! I will test tomorrow.

**Comment by jasonjckn** [comment]
tested, works great, thanks!

**Comment by cddr** [comment]
I'm getting this error again but we're on

```
:dependencies
 [
  [com.fzakaria/slf4j-timbre "0.3.4"]
 ....
  [com.taoensso/timbre "4.3.1"]]
```

**Comment by rufoa** [comment]
Please run `lein deps :tree` and ensure your timbre dependency isn't being shadowed by an earlier version
