### ISSUE TITLE
Use of clojure.string without require

### ISSUE THREAD

**Issue by SevereOverfl0w** [fzakaria/slf4j-timbre#29]
https://github.com/fzakaria/slf4j-timbre/blob/master/src/slf4j_timbre/adapter.clj#L25

This happens to be okay, but may not always be depending on how other libraries decide to perform requires.

**Comment by rufoa** [comment]
Good catch

**Comment by rufoa** [comment]
Fixed in 0.3.10, now available in clojars
Thanks
