### ISSUE TITLE
SLF4j actual binding gets unset when importing dgraph4j

### ISSUE THREAD

**Issue by vxe** [fzakaria/slf4j-timbre#38]
https://github.com/dgraph-io/dgraph4j

Essentially without this project in deps.edn:

```
SLF4J: Actual binding is of type [com.github.fzakaria.slf4j.timbre.TimbreLoggerFactory]
```

adding it results in

```
 SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```

using these dependencies

```
        io.dgraph/dgraph4j {:mvn/version "2.0.2"}
        com.taoensso/timbre {:mvn/version "4.10.0"}
        com.fzakaria/slf4j-timbre {:mvn/version "0.3.19"}
        org.slf4j/slf4j-api {:mvn/version "1.7.21"}
```

Are you able to reproduce and/or know the cause of this?

**Comment by rufoa** [comment]
Thanks for the report. Will investigate

**Comment by rufoa** [comment]
This is a bug in dgraph4j, which lists `org.slf4j/slf4j-simple` as a compile-time dependency in the default scope. Libraries should not propagate specific slf4j bindings to dependent projects - [see the slf4j FAQ](http://www.slf4j.org/faq.html#maven2).

Please file a bug report with dgraph4j, telling them to scope their dependency on `org.slf4j/slf4j-simple` correctly to stop it propagating to other people's projects. You could link them to this comment.

A temporary workaround for you, until dgraph4j fix their project, is to manually exclude it from your project dependencies:
- deps.edn:
`io.dgraph/dgraph4j {:mvn/version "2.0.2" :exclusions [org.slf4j/slf4j-simple]}`
- lein project.clj:
`[io.dgraph/dgraph4j "2.0.2" :exclusions [org.slf4j/slf4j-simple]]`

Please confirm this fixes your problem. Thanks

**Comment by vxe** [comment]
work around worked, and bug report filed.  Great work on this project!
