### ISSUE TITLE
is the `jul` in `[org.slf4j/jul-over-slf4j "1.7.12"]` a typo?

### ISSUE THREAD

**Issue by lsh-0** [fzakaria/slf4j-timbre#4]
I'm getting this when following instructions in README to add deps to project:

`Could not find artifact org.slf4j:jul-over-slf4j:jar:1.7.12 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.slf4j:jul-over-slf4j:jar:1.7.12 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.`

I also couldn't find much mention of that library anywhere via google.

... I was wondering if `[org.slf4j/jul-over-slf4j "1.7.12"]` is a typo of `[org.slf4j/jcl-over-slf4j "1.7.12"]` beneath it ?

If not, this dependency is broken.

**Comment by fzakaria** [comment]
You are right. 
For JUL it is `jul-to-slf4j` becaue JUL is special otherwise the naming convention is to use `over`.

http://www.slf4j.org/legacy.html

I'll edit the README

**Comment by lsh-0** [comment]
Thanks for fixing this.

**Comment by fzakaria** [comment]
Thanks for the PR!

Farid Zakaria
