### ISSUE TITLE
configuration from file

### ISSUE THREAD

**Issue by mirkub** [fzakaria/slf4j-timbre#41]
Hi
I find it very difficult to load the configuration from a config file. Probably because the configuration needs to be compiled, right?
Is there a way of doing it?
Thanks
MK

**Comment by rufoa** [comment]
Sorry to hear you're having problems with this @mirkub

The idea is that you do all config through timbre (and not using e.g. an slf4j `.properties` file)

Timbre's config map is described here: https://github.com/ptaoussanis/timbre/#configuration

You don't usually put this in a separate file. Normally you use `timbre/set-config!`, `timbre/merge-config!`, `timbre/set-level!` etc in your clojure code to configure the logging.

Can you give me more info about what you're trying to do, or show me your code?

**Comment by rufoa** [comment]
I assume this has been resolved so will close it now.

If @mirkub or anyone else is still having problems, please feel free to reopen this issue or to create a new one.
