### ISSUE TITLE
timbre 5.0 support

### ISSUE THREAD

**Issue by rufoa** [fzakaria/slf4j-timbre#42]
https://github.com/ptaoussanis/timbre/releases/tag/v5.0.0

**Comment by jsyrjala** [comment]
Are there any known issues with timbre 5.0.0? At least we are seeing libraries using slf4j to logging at DEBUG level with timbre 5.0.0, when they didn't with timbre 4. with slf4j-timbre 0.3.19

**Comment by rufoa** [comment]
Thanks for letting me know. I haven't yet tested slf4j-timbre with timbre 5.0.0. I will investigate this issue ASAP

**Comment by rufoa** [comment]
I have successfully reproduced this issue and have identified the root cause. It is a consequence of timbre renaming `:level` to `:min-level` in 5.0.0.

When slf4j-timbre is compiled (against timbre 4.10.0), the line `(timbre/with-level :info ...)` macro-expands to `(assoc *config* :level :info)`.

At runtime, your project (with timbre 5 on the classpath) reads the value of `:min-level`, which is not set, so defaults to `:debug`.

I will try to figure out the best way to solve this.

**Comment by rufoa** [comment]
@jsyrjala please try `0.3.20`!

**Comment by jsyrjala** [comment]
I tried 0.3.20 and we are still seeing debug logs with timbre 5.x and not seeing them with timbre 4.x.

**Comment by rufoa** [comment]
That is very strange :confused:

Please could you give me as much detail as possible about how your project is triggering this behaviour? A small test case would be ideal.

Many thanks

**Comment by awb99** [comment]
I use it with timbre v5, but I get this warning printed in console:

```
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/home/andreas/.m2/repository/com/fzakaria/slf4j-timbre/0.3.21/slf4j-timbre-0.3.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```

**Comment by devurandom** [comment]
> I use it with timbre v5, but I get this warning printed in console:
> 
> ```
> SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
> SLF4J: Ignoring binding found at [jar:file:/home/andreas/.m2/repository/com/fzakaria/slf4j-timbre/0.3.21/slf4j-timbre-0.3.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> ```

What you are seeing is probably #45.

**Comment by masterbuilder99** [comment]
Any update on updating this library to timbre v5?

**Comment by awb99** [comment]
@rufoa I see you have forked this repo. Is your fork working? I find it very annoying that since timbre 5 this library did break don. It really should be a simple thing...  What could be done  is to make a different artefact, and then the different timbre versions are easily visible.

**Comment by rufoa** [comment]
Hi guys, sorry the lack of timbre 5 support is causing annoyance. I have most of the code ready but have been very short of time recently due to work. I hope to be able to dedicate some time to getting this finished soon, and will announce here when it is ready. Thanks for your continued patience.

**Comment by awb99** [comment]
Hi! Any news in this?

**Comment by rufoa** [comment]
@awb99 yes! Please try out [the new snapshot](https://clojars.org/com.fzakaria/slf4j-timbre/versions/0.3.21-6-9f1d565-SNAPSHOT) and let me know if it works for you.

I've not yet finished my overhaul of the integration tests, which should give me more confidence that everything works with different library versions and configurations. But I can't keep you waiting for that!!
