### ISSUE TITLE
slf4j-timbre compiled with JDK 1.8

### ISSUE THREAD

**Issue by markjfisher** [fzakaria/slf4j-timbre#5]
Is there any reason why this has been released with JDK 1.8?

I'm getting following

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/slf4j/impl/StaticLoggerBinder : Unsupported major.minor version 52.0, compiling:(core.clj:268:1)
at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3628)
at clojure.lang.Compiler$DefExpr.eval(Compiler.java:439)
at clojure.lang.Compiler.eval(Compiler.java:6787)
```

It's coming from HOME/.m2/repository/com/fzakaria/slf4j-timbre/0.2.1/slf4j-timbre-0.2.1.jar in my classpath.

```
$ javap -cp . -verbose org.slf4j.impl.StaticLoggerBinder | grep major
  major version: 52
```

I'm using 1.7 still for my projects, and can't move to 1.8, this is the only lib causing errors.

Also, I can't seem to override this because org.slf4j.impl.StaticLoggerBinder is included directly in the jar (as opposed to by dependency), then even adding a specific 'org.slf4j/slf4j-simple "1.7.13"' in my dependency is being overridden by slf4j-timbre.

Is there another solution to this I'm missing?

**Comment by fzakaria** [comment]
I dont think there's any need for it to be 1.8.

My understanding is the following change will work:

```
:javac-options ["-target" "1.7" "-source" "1.7" "-Xlint:-options"]
```

Can you add that to a fork and if it fixes the problem I can merge in the PR.

**Comment by rufoa** [comment]
Fixed in 0.2.2

@fzakaria: could you please push to clojars

**Comment by fzakaria** [comment]
Will do later tonight.

**Comment by fzakaria** [comment]
deployed.
Sorry it took so long.
