### ISSUE TITLE
Including `slf4j-timbre` in Timbre core's unit tests?

### ISSUE THREAD

**Issue by ptaoussanis** [fzakaria/slf4j-timbre#71]
Hi there!

What would you think of perhaps having a unit test in Timbre's core for `slf4j-timbre`? Might be a good way to help ensure that I don't accidentally break anything on your side when releasing new versions of Timbre.

If you agree this might make sense, could I maybe impose on you to submit a small PR against Timbre? I'm not too familiar with `slf4j-timbre` internals or config - so you'd probably be in a better position than me to choose a useful test.

Otherwise I'll try take a look at this myself next time I'm doing batched work on Timbre.

Thanks so much for all your work on slf4j-timbre!

Cheers :-)

**Comment by rufoa** [comment]
Hi @ptaoussanis! That sounds like it could be a good idea. I'm similarly largely unfamiliar with timbre's internals, but I'll look into what can be done.

**Comment by ptaoussanis** [comment]
@rufoa Hi Rufus! Just an update to share that I'm planning to add out-the-box SLF4J integration to an upcoming version of Timbre later this year.

I've got a working prototype ready for [Telemere](https://github.com/taoensso/telemere) and plan to back-port that to Timbre along with many other improvements around [Jul-Aug](https://www.taoensso.com/roadmap). This will include Marker and MDC support, and will include tests in Timbre's suite.

Mentioning now since I suspect the current issue probably won't be worth the effort any more.

To be clear: I _really_ appreciate all your awesome work over the years on `slf4j-timbre` - and I'm sure its many users do too! But on reflection I do think it's probably a better idea to have SLF4J support directly integrated in core to help prevent accidental breakages and to ease testing, etc.

If you're up for it, I'd love to ping you closer the time to get your expertise on reviewing the final implementation?

**Comment by rufoa** [comment]
Thanks @ptaoussanis! This sounds like a great move which I support entirely. Thank you for your continued work on this and your kind words.

It's regrettable that I can no longer dedicate to this project the time and attention which it deserves. I also agree that first-class support for SLF4J in timbre makes most sense. This is bound to simplify the implementation of features, and in some cases may be the only way to properly achieve this (I'm thinking of compile-time elision).

Do feel free to contact me if I can be of any help in future! (or when it's time to archive this project and put a message in the readme)

**Comment by fzakaria** [comment]
You've been a great steward / maintainer @rufoa 🙏

**Comment by ptaoussanis** [comment]
Hi @fzakaria, @rufoa!

I've just pushed [Timbre v6.6.0-RC1](https://github.com/taoensso/timbre/releases/tag/v6.6.0-RC1) which includes built-in SLF4J support.

The relevant details:

- [Docs](https://github.com/taoensso/timbre/wiki/4-Interop#java-logging) (minimal for now, just how to set up)
- [Clojure source](https://github.com/taoensso/timbre/blob/master/slf4j/src/taoensso/timbre/slf4j.clj) and [tests](https://github.com/taoensso/timbre/blob/171ed05e2a074386c1c662c89b6a9f42fe33d0c6/test/taoensso/timbre_tests.cljc#L168)
- [Java source](https://github.com/taoensso/timbre/tree/master/slf4j/src/java/com/taoensso/timbre/slf4j)

Feedback very much welcome if either of you have any suggested changes or improvements!

And again a huge thanks to you both for all the awesome work on `slf4j-timbre` over the years 🙏🙏

**Edit to add**: I believe this issue can now be closed.
