### ISSUE TITLE
Incompatable w/ slf4j-jdk-platform-logging 2.0

### ISSUE THREAD

**Issue by rschmukler** [fzakaria/slf4j-timbre#72]
Thanks for all your work on this library and the upgrade to slf4j 2.0!

I've noticed that using slf4j-timbre with a library that depends on [slf4j-jdk-platform-logging](https://github.com/qos-ch/slf4j/blob/master/slf4j-jdk-platform-logging/src/main/java/org/slf4j/jdk/platform/logging/SLF4JPlatformLogger.java) will result in the JVM exiting after attempting to call functions that don't exist in `adapter.clj`.

Specifically it looks like the `adapter` is expected to provide a `-isEnabledForLevel` method as well as handle a call within `performLog` to a new method `-makeLoggingEventBuilder`. 

I played with implementing the methods locally but wanted to confirm if this is actually something that `adapter.clj` should handle. Similarly, is there a reference to any other methods that `2.0` is expecting the adapter to implement that are also missing? Alternatively, perhaps this is an issue with the `SLF4JPlatformLogger` implementation using non-standard methods?

Again, thanks for all the work in this and sorry I am not familiar enough with the SLF4J ecosystem / 2.0 upgrade to know what the right course of action is.

**Comment by ptaoussanis** [comment]
@rschmukler Hi Ryan - in case this is still relevant for you, you might want to try [Timbre v6.6.0-RC1](https://github.com/taoensso/timbre/releases/tag/v6.6.0-RC1) which now includes [built-in SLF4J(v2) support](https://github.com/taoensso/timbre/wiki/4-Interop#java-logging).

**Comment by rschmukler** [comment]
Thanks @ptaoussanis - much appreciated it! Probably can just close this issue then.
