### ISSUE TITLE
possible bug with timbre 6.5.0

### ISSUE THREAD

**Issue by vxe** [fzakaria/slf4j-timbre#82]
I'm on a deadline and don't have time to dig into this but a project with the following

* https://github.com/clj-python/libpython-clj/blob/master/deps.edn
* https://github.com/clojupyter/clojupyter/blob/master/deps.edn

was running into this error:

```
Caused by: clojure.lang.ArityException: Wrong number of args (12) passed to: taoensso.timbre/-log!
        at clojure.lang.AFn.throwArity(AFn.java:429)
```

and was fixed with

```
        com.fzakaria/slf4j-timbre   {:mvn/version "0.4.1"
                                     :exclusions [com.taoensso/timbre]}
```

**Comment by rufoa** [comment]
Thanks @vxe. Glad you got it working. This project will soon be replaced by native slf4j support in timbre.
